language: node_js

node_js:
  - stable

notifications:
  email:
    on_success: never
    on_failure: always

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - "node_modules"

install: yarn

script: yarn test

# deploy:
#   provider: script
#   skip_cleanup: true
#   script: yarn run semantic-release
#   on:
#     branch: master

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn run semantic-release
      # on:
      #   branch: master